# Generated by Django 5.0.3 on 2024-03-13 16:44

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=api.models.NumericPhoneField(max_length=20),
        ),
    ]
